export const PROCESS_STATUS = {
  PROCESSING: "0",
  SUCCESSFULL: "1",
  FAILED: "2",
};

export const PROCESSING = PROCESS_STATUS.PROCESSING;
export const SUCCESSFULL = PROCESS_STATUS.SUCCESSFULL;
export const FAILED = PROCESS_STATUS.FAILED;


export const DASHBOARD_PAGE_SIZE = 10;
